//-- (automatically generated by watch-headers.py)
#include "./SimSystem.h"
#include "../systems/CameraSystem.h"
namespace sundile {
	namespace Systems {
		void init(SmartSim _sim) {
			CameraSystem::init(_sim);
		}
	}
}