//-- (automatically generated by watch-headers.py)
//--
//-- EXPORT functions
//--
#include "CameraSystem.h"
#include "MeshSystem.h"
#include "ModelSystem.h"
#include "PhysicsSystem.h"
#include "RenderSystem.h"
#include "ShaderSystem.h"

namespace sundile {
	namespace Systems {
		void init(SmartEVW evw) {
			evw->dispatcher.sink<SceneInitEvent>().connect<CameraSystem::init>();
			evw->dispatcher.sink<SceneInitEvent>().connect<InputSystem::init>();
			evw->dispatcher.sink<WindowInitEvent>().connect<InputSystem::windowInit>();
			evw->dispatcher.sink<SceneInitEvent>().connect<RenderSystem::init>();

			EventSystem::initAll();
		}
	}
}